from datetime import datetime

from sqlalchemy import (
    Column,
    DateTime,
    Integer,
    String,
    BigInteger,
    Boolean,
    Text,
    ForeignKey,
    UniqueConstraint,
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class Folder(Base):
    """Tracked root folders from the config file."""

    __tablename__ = "folders"

    id = Column(Integer, primary_key=True)
    path = Column(String, nullable=False, unique=True)
    added_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_scanned_at = Column(DateTime, nullable=True)

    images = relationship("Image", back_populates="folder", cascade="all, delete-orphan")


class Image(Base):
    """An indexed image file."""

    __tablename__ = "images"

    id = Column(Integer, primary_key=True)

    # Identity
    hash = Column(String(64), nullable=False, unique=True, index=True)  # SHA-256
    path = Column(String, nullable=False, unique=True)

    # Parent folder (nullable: file may have been found outside a tracked root)
    folder_id = Column(Integer, ForeignKey("folders.id", ondelete="SET NULL"), nullable=True)
    folder = relationship("Folder", back_populates="images")

    # File metadata
    mimetype = Column(String(64), nullable=True)   # e.g. "image/jpeg"
    width = Column(Integer, nullable=True)          # pixels
    height = Column(Integer, nullable=True)         # pixels
    size_bytes = Column(BigInteger, nullable=True)  # file size on disk

    # Caption generated by a VLM — stored here, not in ChromaDB
    caption = Column(Text, nullable=True)

    # Embedding status — tracks whether vectors have been computed
    image_embedded = Column(Boolean, default=False, nullable=False)
    text_embedded = Column(Boolean, default=False, nullable=False)

    # Timestamps
    indexed_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    __table_args__ = (
        UniqueConstraint("hash", name="uq_images_hash"),
    )

    def __repr__(self) -> str:
        return f"<Image hash={self.hash[:8]}… path={self.path}>"
